import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bulma/css/bulma.css'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState } from 'react'





export default function swap() {

  const [error, setError] = useState ('')
  const [address, setAddress] = useState()
  const [web3, setWeb3] = useState()
  const [bcContract, setBcContract] = useState()
  const [balance, setBalance] = useState("0")
  const [inputValue1, setInputvalue1] = useState()
  const [inputValue2, setInputvalue2] = useState()
  const [inputValue3, setInputvalue3] = useState()
  const [betPlayers, setBetPlayers] = useState([])
  const [totalValue, setTotalValue] = useState()


  // const router = useRouter()

  // If i want to rout somewhere by button i hanlde it this way:
  // const handleClick = () => {
  //   console.log('input your amount');
  //   router.push('/liquidity')
  // }
  // Then i can use handleClick in: button/onClick

  // const connectWalletHandler = async () => {
  //   setError('')
  //   if (typeof window !== "undefined" && typeof window.ethereum !== "undefined"){
  //       try{
  //           const accounts = await ethereum.request({ method: 'eth_requestAccounts' });
  //           const account = accounts[0];
  //           setAddress(account)
  //           // const provider = new ethers.providers.Web3Provider(web3.currentProvider);
  //           // setWeb3(web3)
  //           // const accounts = await web3.eth.getAccounts();
            
  //           document.getElementById("connectButton").innerHTML = "Connected!"
            
  //       } catch (err) {
  //           setError(err.message)
  //       }
        
  //   } else {
  //       console.log("please install metamask")
  //   }
  // }


  // onChange={(e) => setInputvalue1(e.target.value)}

  return (
    <div className={styles.container}>
      <Head>
        <title>Invesweet Dex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className='box'>
          <div className="tabs  is-centered ">
            <ul className=''>
              <li className="is-active"><a>Swap</a></li>
              <li><Link href='/liquidity'>Pool</Link></li>
              <li><Link href='/faucet'>Faucet</Link></li>
            </ul>
          </div>
        <div className='box'>
          <label className="label">IST to USDC</label>
          <div className="control">
            <div className="navbar-item is-hoverable navbar-end ">
            </div>
            <input className="input mt-2" value={""} type="text" placeholder="Input IST amount..."  />
            <input className="input mt-2" value={""} type="text" placeholder="0" />
            <button className='button is-link mt-2 mr-2'>Approve</button>
            <button className='button is-link mt-2' disabled>Swap</button>
          </div>
        </div>
        <div className='box'>
          <label className="label">USDC to IST</label>
          <div className="control">
            <div className="navbar-item is-hoverable navbar-end ">
            </div>
            <input className="input mt-2" value={""} type="text" placeholder="Input USDC amount..."  />
            <input className="input mt-2" value={""} type="text" placeholder="0" />
            <button className='button is-link mt-2 mr-2'>Approve</button>
            <button className='button is-link mt-2' disabled>Swap</button>
          </div>
        </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
